/** Common equity sector labels for exclusion preferences (searchable multi-select). */
export const INVESTMENT_SECTOR_OPTIONS: readonly string[] = [
  'Aerospace & Defense',
  'Airlines',
  'Auto Components',
  'Automobiles',
  'Banks',
  'Beverages',
  'Biotechnology',
  'Building Materials',
  'Capital Markets',
  'Chemicals',
  'Commercial Services',
  'Communications Equipment',
  'Construction & Engineering',
  'Consumer Finance',
  'Consumer Staples Distribution',
  'Containers & Packaging',
  'Diversified Financials',
  'Electric Utilities',
  'Electrical Equipment',
  'Energy Equipment & Services',
  'Food Products',
  'Gas Utilities',
  'Health Care Equipment',
  'Health Care Providers',
  'Hotels & Leisure',
  'Household Products',
  'Independent Power',
  'Industrial Conglomerates',
  'Insurance',
  'Internet Software & Services',
  'IT Services',
  'Leisure Products',
  'Machinery',
  'Media',
  'Metals & Mining',
  'Multi-Utilities',
  'Oil & Gas Exploration',
  'Oil & Gas Storage',
  'Paper & Forest',
  'Personal Products',
  'Pharmaceuticals',
  'Real Estate Management',
  'REITs',
  'Road & Rail',
  'Semiconductors',
  'Software',
  'Specialty Retail',
  'Technology Hardware',
  'Telecommunication Services',
  'Textiles & Apparel',
  'Tobacco',
  'Trading Companies',
  'Transportation Infrastructure',
  'Water Utilities',
] as const;
